global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "openwebui-exporter"
    static_configs:
      - targets: ["metrics-exporter:8000"]
    metrics_path: /metrics

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "openwebui-app"
    static_configs:
      - targets: ["open-webui:8080"]
    metrics_path: /metrics
    
  - job_name: "openwebui-internal"
    static_configs:
      - targets: ["open-webui:8080"]
    metrics_path: /metrics
